export const TOGGLESIDEBAR = 'TOGGLESIDEBAR';
export const TOGGLEPROFILESETTINGSSIDEBAR = 'TOGGLEPROFILESETTINGSSIDEBAR';
export const CLOSEMODAL = 'CLOSEMODAL';
export const OPENMODAL = 'OPENMODAL';
