export const SIGNINREQUEST = 'SIGNINREQUEST';
export const SIGNINSUCCESS = 'SIGNINSUCCESS';
export const SIGNINFAILURE = 'SIGNINFAILURE';

export const SIGNUPREQUEST = 'SIGNUPREQUEST';
export const SIGNUPSUCCESS = 'SIGNUPSUCCESS';
export const SIGNUPFAILURE = 'SIGNUPFAILURE';

export const FORGOTPASSWORDREQUEST = 'FORGOTPASSWORDREQUEST';
export const FORGOTPASSWORDSUCCESS = 'FORGOTPASSWORDSUCCESS';
export const FORGOTPASSWORDFAILURE = 'FORGOTPASSWORDFAILURE';

export const RESETPASSWORDREQUEST = 'RESETPASSWORDREQUEST';
export const RESETPASSWORDSUCCESS = 'RESETPASSWORDSUCCESS';
export const RESETPASSWORDFAILURE = 'RESETPASSWORDFAILURE';

export const LOGOUT = 'LOGOUT';
