export const GETAUTHUSERDATAREQUEST = 'GETAUTHUSERDATAREQUEST';
export const GETAUTHUSERDATASUCCESS = 'GETAUTHUSERDATASUCCESS';
export const GETAUTHUSERDATAFAILURE = 'GETAUTHUSERDATAFAILURE';

export const GETAUTHUSERSETTINGSDATAREQUEST = 'GETAUTHUSERSETTINGSDATAREQUEST';
export const GETAUTHUSERSETTINGSDATASUCCESS = 'GETAUTHUSERSETTINGSDATASUCCESS';
export const GETAUTHUSERSETTINGSDATAFAILURE = 'GETAUTHUSERSETTINGSDATAFAILURE';

export const UPDATEPROFILEINPUTFIELDS = 'UPDATEPROFILEINPUTFIELDS';

export const UPDATEUSERPROFILEDETAILSREQUEST = 'UPDATEUSERPROFILEDETAILSREQUEST';
export const UPDATEUSERPROFILEDETAILSSUCCESS = 'UPDATEUSERPROFILEDETAILSSUCCESS';
export const UPDATEUSERPROFILEDETAILSFAILURE = 'UPDATEUSERPROFILEDETAILSFAILURE';
export const USERLOGOUT = 'USERLOGOUT';

export const GETNOTIFICATIONREQUEST = 'GETNOTIFICATIONREQUEST';
export const GETNOTIFICATIONSUCCESS = 'GETNOTIFICATIONSUCCESS';
export const GETNOTIFICATIONFAILURE = 'GETNOTIFICATIONFAILURE';

export const MARKALLNOTIFICATIONASREADREQUEST = 'MARKALLNOTIFICATIONASREADREQUEST';
export const MARKALLNOTIFICATIONASREADSUCCESS = 'MARKALLNOTIFICATIONASREADSUCCESS';
export const MARKALLNOTIFICATIONASREADFAILURE = 'MARKALLNOTIFICATIONASREADFAILURE';

export const GETUSERBYUSERNAMEREQUEST = 'GETUSERBYUSERNAMEREQUEST';
export const GETUSERBYUSERNAMESUCCESS = 'GETUSERBYUSERNAMESUCCESS';
export const GETUSERBYUSERNAMEFAILURE = 'GETUSERBYUSERNAMEFAILURE';
